<?php

namespace backend\assets;

use yii\web\AssetBundle;
use yii\web\View;

class GlobalMessagesAsset extends AssetBundle
{
    /**
     * @var string
     */
    public $sourcePath = '@backend/resources/js/system/global-messages';

    public function init()
    {
        $this->jsOptions['position'] = View::POS_END;
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @var array
     */
    public $js = [
        'index.js'
    ];

}
