version: "3.2"

services:
  app:
    build: docker/php
    volumes:
      - ./:/app
    depends_on:
      - mysql
      - mailcatcher
    env_file:
      - .env
    restart: always
  webpacker:
    image: node:9-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: /bin/true

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672

  nginx:
    image: nginx:1.12-alpine
    ports:
      - 20081:80
    volumes:
      - ./:/app
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
    depends_on:
      - app
    restart: always

  mailcatcher:
    image: schickling/mailcatcher:latest
    ports:
      - 1080:1080
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ../database/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=media_site_database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    restart: always
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions
  redis:
    image: "redis:alpine"
    ports:
     - "6379:6379"
    restart: always